require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - Gemfile
    - .pryrc

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Lint/HandleExceptions:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/factories/**/*.rb"
    - "spec/support/**/*.rb"
    - lib/tasks/auto_annotate_models.rake

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false